# Generated by Django 5.1.3 on 2025-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='mobileno',
            field=models.CharField(max_length=20),
        ),
    ]
